### PR TITLE
Link deserialization

### PR DESCRIPTION
**Pull request by lizj28**
This change will deserialize links in the json api request.  So if you have a payload that looks like:
```js
{
      data: [
        {
          type: 'users',
          id: '1',
          attributes: {
            'first-name': 'Joe',
            'last-name': 'Doe',
          },
          links: {
            self: 'https://example.org/users/1',
            action: 'https://example.org/action',
          },
          relationships: {
            address: {
              data: {
                type: 'addr',
                id: '1',
              },
              links: {
                self: 'https://example.org/address/1/relationships/address',
                related: 'https://example.org/address/1',
              },
            },
            images: {
              data: [
                { type: 'img', id: '1' },
                { type: 'img', id: '2' },
              ],
            },
          },
        },
      ],
      included: [
        {
          type: 'addr',
          id: '1',
          attributes: {
            street: 'Street 1',
          },
        },
      ],
    }
```

Will produce:
```js
{
        id: '1',
        firstName: 'Joe',
        lastName: 'Doe',
        links: {
          self: 'https://example.org/users/1',
          action: 'https://example.org/action',
        },
        address: {
          id: '1',
          street: 'Street 1',
          links: {
            self: 'https://example.org/address/1/relationships/address',
            related: 'https://example.org/address/1',
          },
        },
        images: [{ id: '1' }, { id: '2' }],
      }
```

### CODE REVIEW

**Comment by lizj28** [comment]
@andersondanilo could you let me know your thoughts on this?  We need it to continue to use your library in our application.

**Comment by lizj28** [comment]
@andersondanilo I'm trying to work through the actions issues but it's gonna be tricky if the workflows don't run automatically.  Let me know if there's a better way to work through those! All the steps in the actions are working locally for me now so hopefully we have more luck this way!

**Review by andersondanilo — APPROVED** [review]
Looks good to me, i will test what is happening with the workflow

**Comment by lizj28** [comment]
Thank you for your help getting this through @andersondanilo !

**Pull request merged**
